# Site settings
title: Pete Russell - NZ PPL Training Notes
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nzppl.peterussell.me" # the base hostname & protocol for your site
twitter_username: nz_pete
github_username:  peterussell

# Build settings
markdown: kramdown
